# Thinkpadism — the user half, applied through Home Manager by nixos.nix.
#
# The bar, Hyprland, the theme, and the essential programs: WezTerm, Yazi,
# Neovim, Git and LibreWolf. Anything else is up to you — add it to your
# own configuration.nix.
{
  self,
  cfg,
}: {
  config,
  lib,
  pkgs,
  osConfig,
  ...
}: let
  pkgsFor = self.packages.${pkgs.stdenv.hostPlatform.system};
  configs = "${self}/configs";

  isDark = cfg.theme == "thinkpad-dark";
  gtkTheme =
    if isDark
    then "ThinkpadismPlatinumDark"
    else "ThinkpadismPlatinum";

  shell = lib.getExe pkgsFor.thinkpadism;
  terminal = "wezterm";
  luaString = s: ''"${lib.escape ["\\" "\""] s}"'';

  # The launcher and appearance menu are popups reached over the bar's IPC
  # socket, one per monitor, so the command names the focused one.
  ipc = call: "${shell} ipc call appLauncher_$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name') ${call}";

  neovim = import ./neovim.nix {inherit pkgs;};

  # settings.json is state the bar rewrites whenever you change theme or
  # wallpaper, so it is seeded once and then left alone.
  seedSettings = pkgs.writeShellScript "thinkpadism-seed-settings" ''
    set -eu
    file="''${XDG_CONFIG_HOME:-$HOME/.config}/thinkpadism/settings.json"
    if [ -e "$file" ]; then exit 0; fi
    mkdir -p "$(dirname "$file")"
    ${lib.getExe pkgs.jq} --arg theme ${cfg.theme} '.settings.currentTheme = $theme' \
      ${configs}/thinkpadism/settings.json > "$file"
    chmod 0644 "$file"
  '';

  # Copies the wallpapers once. A stamp file, so ones you delete stay deleted.
  installWallpapers = pkgs.writeShellScript "thinkpadism-install-wallpapers" ''
    set -eu
    dir="$HOME/Pictures/Wallpapers"
    stamp="''${XDG_STATE_HOME:-$HOME/.local/state}/thinkpadism/wallpapers-installed"
    if [ -e "$stamp" ]; then exit 0; fi
    mkdir -p "$dir" "$(dirname "$stamp")"
    cp ${pkgsFor.thinkpadism-wallpapers}/share/wallpapers/thinkpadism/*.png "$dir/"
    chmod u+w "$dir"/*.png
    touch "$stamp"
  '';
in {
  home.stateVersion = lib.mkDefault osConfig.system.stateVersion;

  home.packages = with pkgs; [
    pkgsFor.thinkpadism # the bar
    wezterm
    neovim

    # What the bar, the keybinds and the autostart call.
    hyprpaper
    hypridle
    hyprlock
    hyprshot
    wl-clipboard
    networkmanagerapplet # nm-applet
    wiremix # audio TUI
    btop # performance TUI
    brightnessctl
    playerctl
    wireplumber # wpctl
    jq
    dconf

    # ThinkpadismIcons has no status icons; it falls back to Papirus for
    # the bluetooth and network icons the tray menus ask for.
    papirus-icon-theme
  ];

  home.sessionVariables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
  };

  home.activation = {
    thinkpadismSettings = lib.hm.dag.entryAfter ["writeBoundary"] "run ${seedSettings}";
    thinkpadismWallpapers = lib.hm.dag.entryAfter ["writeBoundary"] "run ${installWallpapers}";
  };

  #####################################################################
  # Hyprland — configured in Lua (Hyprland 0.55+)
  #####################################################################

  wayland.windowManager.hyprland = {
    enable = true;
    configType = "lua";
    # Installed by the NixOS module.
    package = null;
    portalPackage = null;
    # UWSM owns the session target; Home Manager doing it too races it.
    systemd.enable = false;

    extraLuaFiles = {
      # The one generated file: commands, with the bar by store path.
      "lib.programs" = {
        autoLoad = false;
        content = ''
          -- Generated by the Thinkpadism NixOS module. Do not edit.
          return {
              terminal       = ${luaString terminal},
              browser        = "librewolf",
              files          = ${luaString "${terminal} -e yazi"},
              tuiNetwork     = ${luaString "${terminal} -e nmtui"},
              tuiAudio       = ${luaString "${terminal} -e wiremix"},
              tuiPerformance = ${luaString "${terminal} -e btop"},
              shell          = ${luaString shell},
              menu           = ${luaString (ipc "toggleAppLauncher")},
              appearanceMenu = ${luaString (ipc "toggleThemeMenu")},
              toggleDarkMode = ${luaString (ipc "toggleDarkMode")},
              lock           = "hyprlock",
          }
        '';
      };
      "lib.theme" = {
        autoLoad = false;
        content = "${configs}/hypr/lua/lib/theme.lua";
      };

      # Loaded in name order; later calls win in Hyprland.
      "10-options" = "${configs}/hypr/lua/10-options.lua";
      "20-rules" = "${configs}/hypr/lua/20-rules.lua";
      "30-binds" = "${configs}/hypr/lua/30-binds.lua";
      "40-keys" = "${configs}/hypr/lua/40-keys.lua";
      "50-autostart" = "${configs}/hypr/lua/50-autostart.lua";
      "90-session" = ''
        -- Generated by the Thinkpadism NixOS module.
        hl.config({ input = { kb_layout = ${luaString cfg.keyboardLayout}, kb_options = "grp:alt_shift_toggle" } })

        -- Hackneyed is an XCursor theme, not a hyprcursor one. Turning
        -- hyprcursor off makes Hyprland load it directly instead of
        -- falling back to its own built-in arrow.
        hl.config({ cursor = { enable_hyprcursor = false } })
        hl.env("XCURSOR_THEME", "Hackneyed")
        hl.env("XCURSOR_SIZE", "24")
        hl.on("hyprland.start", function()
            hl.exec_cmd("hyprctl setcursor Hackneyed 24")
        end)
      '';
    };
  };

  # hypridle, hyprlock and hyprpaper are still hyprlang; only Hyprland moved.
  xdg.configFile = {
    "hypr/hyprpaper.conf".source = "${configs}/hypr/hyprpaper.conf";
    "hypr/hypridle.conf".source = "${configs}/hypr/hypridle.conf";
    "hypr/hyprlock.conf".source = "${configs}/hypr/hyprlock.conf";

    "wezterm/wezterm.lua".source = "${configs}/wezterm/wezterm.lua";
    "wezterm/colors.lua".source = "${configs}/wezterm/colors.lua";

    "yazi/yazi.toml".source = "${configs}/yazi/yazi.toml";
    "yazi/theme.toml".source = "${configs}/yazi/theme.toml";
    "yazi/keymap.toml".source = "${configs}/yazi/keymap.toml";

    "nvim" = {
      source = "${configs}/nvim";
      recursive = true;
    };
  };

  programs.yazi.enable = true;
  programs.git.enable = true;

  #####################################################################
  # Dark, everywhere
  #
  # GTK3, GTK4, Qt and the browser each decide separately whether to be
  # dark. Set only one and you get a dark desktop with white menus and a
  # white browser, so all four are set here from the same theme.
  #####################################################################

  gtk = {
    enable = true;
    colorScheme =
      if isDark
      then "dark"
      else "light";
    theme = {
      name = gtkTheme;
      package = pkgsFor.thinkpadism-gtk-theme;
    };
    gtk4.theme = config.gtk.theme;
    iconTheme = {
      name = "ThinkpadismIcons";
      package = pkgsFor.thinkpadism-icons;
    };
  };

  # Hackneyed: the Windows 3.x / NT cursor set. home.pointerCursor sets it
  # for GTK and X11 apps and as the "default" fallback theme; Hyprland
  # itself is told in 90-session.lua, since UWSM starts it before the
  # user's session variables exist.
  home.pointerCursor = {
    enable = true;
    name = "Hackneyed";
    package = pkgs.hackneyed;
    size = 24;
    gtk.enable = true;
    x11.enable = true;
  };

  # The bar's tray menus are real Qt menus; this makes them follow GTK.
  qt = {
    enable = true;
    platformTheme.name = "gtk3";
  };

  # What GTK4 apps and the portal (and so the browser) actually read.
  dconf.settings."org/gnome/desktop/interface" = {
    color-scheme =
      if isDark
      then "prefer-dark"
      else "prefer-light";
    gtk-theme = gtkTheme;
    icon-theme = "ThinkpadismIcons";
  };

  services.mako = {
    enable = true;
    settings = {
      font = "monospace 10";
      background-color =
        if isDark
        then "#1b1b1bf0"
        else "#d6d3cef0";
      text-color =
        if isDark
        then "#e6e4e1"
        else "#121212";
      border-color = "#b3121d";
      border-size = 1;
      border-radius = 0;
      default-timeout = 6000;
    };
  };

  #####################################################################
  # Browser: LibreWolf, dark from the first frame
  #####################################################################

  programs.librewolf = {
    enable = true;
    settings = {
      # resistFingerprinting forces every page light; it has to go for
      # dark mode to apply at all.
      "privacy.resistFingerprinting" = false;
      "privacy.fingerprintingProtection" = true;
      # Stay logged in between sessions.
      "privacy.clearOnShutdown_v2.cookiesAndStorage" = false;
      "privacy.clearOnShutdown_v2.historyFormDataAndDownloads" = false;
      "webgl.disabled" = false;

      "layout.css.prefers-color-scheme.content-override" =
        if isDark
        then 0
        else 1;
      "browser.theme.toolbar-theme" =
        if isDark
        then 0
        else 1;
      # The colour painted before the first page loads — the white flash.
      "browser.display.background_color.dark" = "#141414";
    };
  };
}
