# Hyprland, hyprpaper, hypridle and hyprlock.
#
# Hyprland 0.55 deprecated hyprlang in favour of Lua, and 0.56 is what
# nixpkgs-unstable ships, so the compositor config is Lua. The other three
# Hypr* programs still take hyprlang and are copied as-is.
#
# The Lua modules live in configs/hypr/lua and are installed verbatim --
# they are meant to be read and edited. Everything machine-specific is
# funnelled through lib/programs.lua, which is the only file generated
# from Nix, so the modules themselves never need to know a store path.
self: {
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs.thinkpadism;
  configs = "${self}/configs";

  inherit (lib) mkIf getExe;

  # Launch the TUI tools inside the configured terminal.
  inTerminal = tool: "${cfg.terminal} -e ${tool}";

  shellExe = getExe cfg.package;

  # The launcher and appearance menu are Quickshell popups reached over
  # its IPC socket. The handler is registered per-monitor, so the target
  # has to name the focused one -- hence the command substitution, which
  # runs because exec_cmd hands the string to sh -c.
  focusedMonitor = "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name')";
  ipc = call: "${shellExe} ipc call appLauncher_${focusedMonitor} ${call}";

  luaString = s: ''"${lib.escape ["\\" "\""] s}"'';

  # The one generated Lua file. Everything the shipped modules need to
  # know about this particular machine arrives through here.
  programsLua = ''
    -- Generated by the Thinkpadism Home Manager module. Do not edit;
    -- set programs.thinkpadism.* instead.
    --
    -- Commands are absolute store paths wherever the shell itself is
    -- involved, so a bind can never launch a stale build because $PATH
    -- changed mid-session.

    local M = {}

    M.terminal    = ${luaString cfg.terminal}
    M.fileManager = ${luaString cfg.fileManager}
    M.browser     = ${luaString cfg.browser}

    M.tuiFiles       = ${luaString (inTerminal cfg.tools.files)}
    M.tuiNetwork     = ${luaString (inTerminal cfg.tools.network)}
    M.tuiAudio       = ${luaString (inTerminal cfg.tools.audio)}
    M.tuiPerformance = ${luaString (inTerminal cfg.tools.performance)}

    M.displays = ${luaString (inTerminal "wdisplays")}

    M.shell          = ${luaString shellExe}
    M.menu           = ${luaString (ipc "toggleAppLauncher")}
    M.appearanceMenu = ${luaString (ipc "toggleThemeMenu")}
    M.toggleDarkMode = ${luaString (ipc "toggleDarkMode")}

    M.screenshotRegion = ${luaString "hyprshot --mode region --clipboard-only"}
    M.screenshotScreen = ${luaString "hyprshot --mode output --output-folder ${config.home.homeDirectory}/Pictures/Screenshots"}
    M.lock             = ${luaString "hyprlock"}

    M.laptopMonitor = ${luaString cfg.hyprland.monitor}
    M.cursorTheme   = ${luaString cfg.hyprland.cursorTheme}

    return M
  '';

  # Machine-specific overrides. Loaded after every shipped module, so
  # these win over the defaults in 10-options.lua.
  machineLua = ''
    -- Generated by the Thinkpadism Home Manager module.

    hl.config({
        input = {
            kb_layout  = ${luaString cfg.hyprland.keyboardLayout},
            kb_options = ${luaString cfg.hyprland.keyboardOptions},
        },
    })
  '';
in {
  config = mkIf (cfg.enable && cfg.hyprland.enable) {
    wayland.windowManager.hyprland = {
      enable = true;

      # Lua, not hyprlang. See the note at the top of this file.
      configType = "lua";

      # Hyprland is started from the display manager or a TTY, and the
      # NixOS module installs the package system-wide.
      package = null;
      portalPackage = null;

      systemd.enable = true;

      extraLuaFiles = {
        # Required by the other modules rather than run on its own.
        "lib.programs" = {
          content = programsLua;
          autoLoad = false;
        };
        "lib.theme" = {
          content = "${configs}/hypr/lua/lib/theme.lua";
          autoLoad = false;
        };

        # Loaded in name order, and order matters: Hyprland lets the
        # latest call for an option win, so the generated machine file
        # goes last, after every shipped default it is meant to override.
        "10-options" = "${configs}/hypr/lua/10-options.lua";
        "20-rules" = "${configs}/hypr/lua/20-rules.lua";
        "30-binds" = "${configs}/hypr/lua/30-binds.lua";
        "40-laptop" = "${configs}/hypr/lua/40-laptop.lua";
        "50-autostart" = "${configs}/hypr/lua/50-autostart.lua";
        "90-machine" = machineLua;
      };

      extraConfig = lib.optionalString (cfg.hyprland.extraLua != "") ''

        -- === programs.thinkpadism.hyprland.extraLua ===
        ${cfg.hyprland.extraLua}
      '';
    };

    # Still hyprlang: only Hyprland itself moved to Lua.
    xdg.configFile = {
      "hypr/hyprpaper.conf".source = "${configs}/hypr/hyprpaper.conf";
      "hypr/hypridle.conf".source = "${configs}/hypr/hypridle.conf";
      "hypr/hyprlock.conf".source = "${configs}/hypr/hyprlock.conf";
    };

    # hyprshot writes here, and refuses to run if the directory is
    # missing.
    home.file."Pictures/Screenshots/.keep".text = "";
  };
}
